### ISSUE TITLE
How to generate Terminal skill icons SVG

### ISSUE THREAD

**Issue by aelbialy** [SofiDevO/primer-blog#30]
First of all, I really love this project. Excellent work here! 

My question is how can I generate another SVG like this one here:
https://github.com/SofiDevO/portfolio-sofidev-garrux/blob/main/public/assets/react.svg

For a skill that is not in the assets folder. Was Iconify used? I can't find that exact SVG in this project in Iconify.

Thank you!

**Comment by SofiDevO** [comment]
@aelbialy 
You can follow this tutorial:

https://www.youtube.com/watch?v=fB8OraROTwk

**Comment by aelbialy** [comment]
Thank you so much @SofiDevO

**Comment by Garruxx** [comment]
@aelbialy I made the library of icons used there. Here is the link https://github.com/Garruxx/ascii-icons

**Comment by aelbialy** [comment]
Thank you so much @Garruxx I'll check it out too.
